# Generated by Django 4.2.3 on 2023-08-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_rename_id_usuario_pessoa_id_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
